# fly.toml app configuration file generated for ipinfo on 2023-07-31T15:54:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ipinfo"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
